config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'whoweare' => 'static_pages#whoweare'

  get 'whatwedo' => 'static_pages#whatwedo'

  get 'connect' => 'static_pages#connectwithus'

  get 'careers' => 'static_pages#careers'

  get 'explore' => 'static_pages#explore'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def whoweare
  end

  def whatwedo
  end

  def connectwithus
  end

  def careers
  end

  def explore
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Harvard College Japan Initiative</title>
<meta name="keywords" content="Harvard Japan Student Organization Campus Tour Careers HLAB" />
<meta name="description" content="HCJI is a student-run organization dedicated to fostering greater interaction and understanding between students from the U.S. and Japan. " />
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial" rel="stylesheet" />
<link href="default.css" rel="stylesheet" type="text/css" media="all" />
<link href="fonts.css" rel="stylesheet" type="text/css" media="all" />
<%= favicon_link_tag 'favicon.png' %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>

<body>
<div id="header-wrapper">
<div id="header" class="container">
	<div id="logo">
<!--     	<span class="icon icon-cog"></span>  -->
    	<img src="assets/logo.png" alt="" />
		<h1><%= link_to "Harvard College Japan Initiative", root_path %></h1>
	</div>
	<div class="no-js" id="menu">
        <nav id="topNav">
            <ul>
            	<li><%= link_to "Home", root_path %></li>
            	<li><%= link_to "Who We Are",   whoweare_path %></li>
            	<li><%= link_to "What We Do",   whatwedo_path %></li>
                    <!-- <ul>  
                        <li><%= link_to "whatwedo#h-lab",   whatwedo_path %></li>
                        <li><%= link_to "whatwedo#hcf",   whatwedo_path %></li>
                        <li><%= link_to "whatwedo#explore",   whatwedo_path %></li>
                        <li><a href="static_pages/whatwedo#h-lab" title="H-LAB">H-LAB</a></li>
                        <li><a href="static_pages/whatwedo#hcf" title="Career Forum">Career Forum</a></li>
                        <li><a href="static_pages/whatwedo#explore" title="HCJI Explore">HCJI Explore</a></li>
                    </ul>    -->             
                </li>
                <li><%= link_to "Connect with Us",  connect_path %></li>
            </ul>
        </nav>
        <script src="js/jquery.js"></script>
        <script src="js/modernizr.js"></script>
    </div>
</div>
</div>


<%= yield %>


<div id="copyright">
	<p>&copy; Harvard College Japan Initiative. All rights reserved.<br>Created by <a href="https://www.linkedin.com/in/kojinoshiba" rel="nofollow">Kojin Oshiba '18</a> & <a href="">Masahiro Kusunoki '17</a>.</p>
	<ul class="contact">
		<li><a href="https://www.facebook.com/HarvardCollegeJapanInitiative?fref=ts" class="icon icon-facebook"><span>Facebook</span></a></li>
		<li><a href="https://twitter.com/HCJIComm" class="icon icon-twitter"><span>Twitter</span></a></li>
	</ul>
</div>

</body>
</html>

app/views/static_pages/careers.html.erb
<style>
.spacer{
	height: 80px;
}
.spacer2{
	height: 30px;
}
</style>

<script>
window.location.replace("http://www.harvardjapancareerforum.com/");
</script>

<div class="wrapper">
	<div id="careers" class="container">
		<div class="content">
			<div class="title">
				<h2>HCJI Career Forum</h2>
			</div>
			<p><img src="assets/careers1.jpg" alt="" width="400px"/>HCJI Career Forum is a 4-day series of events held before and during the annual Boston Career Forum (BCF) that serve as an opportunity for students participating in BCF, to interact and network with companies in a more personal and casual environment on Harvard's campus.</p>
			<p>We provide opportunities for recruiters and students to interact even before BCF begins so that students may network with representatives from various Japanese companies, and companies may do so likewise to their mutual benefit. In 2014, we held four formal information sessions and multiple social events between students and company representatives on Harvard’s campus. A total of 9 companies were represented.</p>
			<p>We also provide housing for non-Harvard students during BCF by connecting them with Harvard students who are willing to host in their dormitories.</p>
			<div class="spacer"></div>

			<h2>History</h2>
			<div id="portfolio" class="container">
				<p>HCJI Career Forum originally began as an opportunity for Harvard students to give back to their friends from Japan. Many students from Harvard visit Japan every year on summer schools, internships and research opportunities. Whenever they go and whatever they do, they are always greeted with great care and hospitality ("Omotenashi"). HCF began as an opportunity where Harvard students can give back to this, by inviting Japanese students to stay at Harvard dormitories during the Boston Career Forum. During this weekend, hotel prices around Boston typically become very high and many students have difficulties getting around in a city that is completely new to them. At HCF, we try to make these students feel at home, staying with their friends on Harvard's campus.</p>

				<p>
				In recent years, HCJI Career Forum has grown to become much more than this, turning into a comprehensive platform that welcomes students and recruiters into this community of Japan-loving-international-students. Our collaborations reach far beyond just Harvard related programs as we welcome students from other Ivy schools, Liberal Arts Colleges and even students from the UK, China and all over the world to take part in our events. We hope to foster a community in which people who love Japan can connect and collaborate with each other to achieve even greater heights in the future.
				</p>
			</div>
			<div class="spacer2"></div>

			<h2>Networking Session</h2>
			<div id="portfolio" class="container">
				<p><img src="assets/coffee.jpg" alt="" width="400px"  style="padding: 0 75px 0 50px"/>
					The Networking Sessions are opportunities for students to be able interact with recruiters on a more personal and casual environment. These events will take place on a cafe located on Harvard's campus (details TBA) and serve as opportunities for recruiters and students to be able to casually converse and exchange information from the day. These are also great events during which fellow students can get to meet each other and make friends with students who have come from all over the world.
				</p>
				<p>
					In the 2014 pilot program, 8 companies participated in this event: AIG, Fourth Valley Concierge Corporation, Japan Tobacco Inc., Mitsui-Sumitomo Finance and Leasing Company, MyNavi Corporation, Rakuten Inc., Toray, Works Application. The participating companies for 2015 will be announced soon.
				</p>
			</div>


			<h2>Housing</h2>
			<div id="portfolio" class="container">
				<p><img src="assets/housing.jpg" alt="" width="400px" style="padding: 0 75px 0 50px"/>
					We will provide free accommodation for participants of the HCJI Career Forum. During the 4 days from the 19th until the 22nd of November, hotel prices around Boston reach extremely high prices; combined with the flight and travel expenses, students must pay up a large sum to participate at BCF.</p>
				<p> This year, we will be providing free housing on Harvard's campus (and on campuses at nearby universities) by matching participants with students at the university who are willing to host. Many students at these Universities are interested in Japan or have homestayed with families in Japan in the past. These students will be more than happy to meet and greet the participants at BCF and this would be a fantastic opportunities for students on both sides. 
				</p>
			</div>
		
			<h2>Schedule 2015</h2>
			<div id="portfolio" class="container">
				<p style="text-align: center">
				<b>November 19th: HCF Welcome Session</b><br>
				Welcome to Harvard! Introductions, Ice-breakers<br>
				Time: 15:00 - 16:00<br>
				Location: TBA<br><br>

				<b>November 19th: Networking Session (Mandatory)</b><br>
				Meet and Greet Fellow Students and Recruiters<br>
				Time: 16:00 - 19:00<br>
				Location: TBA<br><br>

				<b>November 20th: Coffee Chats</b><br>
				Reflecting on Day One<br>
				Time: 20:00 - 22:00<br>
				Location: TBA<br><br>

				<b>November 20th: Coffee Chats</b><br>
				Reflecting on Day Two<br>
				Time: 20:00 - 22:00<br>
				Location: TBA<br><br>

				<b>November 21st: HCF Mixer</b><br>
				Celebrating Our Last Night Together<br>
				Time: 22:00 -<br>
				Location: TBA<br><br>

				<b>November 22nd: Farewell Dinner</b><br>
				Thank yous and Goodbyes<br>
				Time: 18:00 - <br>
				Location: TBA<br>
				</p>
				<div class="spacer2"></div>
			</div>
			<h2>How to Join (Students)</h2>
			<div id="portfolio" class="container">
				<p>
					<b>Requirements & Eligibility</b><br>
					Participants must be an undergraduate student planning to participate in Boston Career Forum from November 20th - 22nd, 2015.<br>
					Participants must be able to arrive on Harvard's campus before 16:00, November 19th.<br>
					The Networking Session on November 19th is mandatory. All other events are optional.<br>
					Participants must be willing to make all effort to participate in HCF Programs, unless with reasonable excuse.<br>
					Preference will be granted to those who have participated in at least one of the following: HLAB, Harvar Project of Asia and International Relations (HPAIR), Harvard College in Asia Program (HCAP), Ryugaku Fellowship (RF), Komatsu Summer School (KSS), Princeton In Ishikawa (PII), Japan-America Student Conference (JASC) and other related programs.<br><br>

					<b>Housing</b><br>
					Please note that housing is limited. Currently (as of September 9th), based on the number of applications, it does not seem likely that we will run a selection.<br>
					If the number of applications increase dramatically, we may need to conduct a selection based on the competitiveness of an applicants resume/ essay. (Applicants will be notified in the event that this selection is to take place).<br>
					People who do not receive housing are still welcome to participate in our events.<br><br>

					<b>Deadlines</b><br>
					Application Deadline: 23:59 September 20th, 2015 (EDT)<br><br>

					<b>Application</b><br>
					
					Please fill out this application if you wish to participate in the event only: <br><a class="button" href="https://docs.google.com/forms/d/1bPCSlsVIjopRAT8WirHiPJObmmk-MtH2q5IqOHcEX-g/viewform?usp=send_form" target="_blank">Event Application</a><br>
					Please fill out this application if you wish to be hosted in a Harvard dormitory room:  <br><a class ="button" href="https://docs.google.com/forms/d/1nKF7ICXO_BAFpgCb3s2zXOK779fiKu_P3PYK6ay-iB8/viewform?edit_requested=true" target="_blank">Housing + Event Application</a><br>

				</p>
				<div class="spacer2"></div>
			</div>
			<h2>How to Join (Companies)</h2>
			<div id="portfolio" class="container">
				<p>Please email hcji.comm@gmail.com for more information.</p>
				<div class="spacer"></div>
			</div>
			<h2>Participating Companies</h2>
			<div id="portfolio" class="container"> 
				<h3>Coming Soon</h3>
				<div class="column1">
					<!-- <div class="box">
						<a href="" target="_blank"><img class="image" src="assets/.jpg" alt="" /></a>
					  	<h3>...</h3>
						<p>...</p>
				    </div> -->
				</div> 
				<!-- <div class="column1">
					<div class="box">
						<img class="image" src="assets/isa.jpg" alt="" height="80px"/>
					  	<h3>ISA</h3>
						<p>Fermentum nibh augue praesent a lacus at urna congue rutrum.</p>
				    </div>
				</div>  -->
			</div>
		</div>
	</div>
</div>

app/views/static_pages/connectwithus.html.erb
<div id="footer">
	<div class="container">
		<div class="fbox">
			<span class="icon icon-envelope"></span>
			<h3>contact us:</h3>
			<p>hcji.comm@gmail.com</p>
			<p>   </p>
			<h3>join our mailing list:</h3>
			<p>sushi-talk@lists.hcs.harvard.edu</p>
		</div>
	</div>
</div>

app/views/static_pages/explore.html.erb
<style>
.spacer{
	height: 80px;
}
.spacer2{
	height: 30px;
}
</style>

<div class="wrapper">
	<div id="careers" class="container">
		<div class="content">
			<div class="title">
				<h2>HCJI Explore</h2>
			</div>
			<p><img src="assets/careers1.jpg" alt="" width="400px"/>HCJI Explore welcomes high school students from all over Japan to "explore" the life at Harvard. We provide them with unforgettable experiences through our on-campus tours, presentations and workshops. All of these programs are created and coordinated by HCJI members and other Harvard student volunteers.</p>
			<p>We offer high schools interested in a more global curriculum a unique opportunity to incorporate on-the-ground experiences at Harvard into their programs. Programs will be developed in coordination with the schools so as to cater to the interests of both the students and the teachers at their request.</p>

			<div class="spacer"></div>

			<h2>For teachers interested...</h2>
			<h3>Things we can offer</h3>
			<ul>
				<li>A student coordinator who will be responsible for making your program at Harvard as educational and unique as possible</li>
				<li>Classrooms inside Harvard campus to hold our programs</li>
				<li>10% discount at the Harvard COOP (a souvenior shop)</li>
				<li>Unforgettable inspiration to the participants ;) </li>
			</ul>
			<p>Please read the following basic guideline below. If this seems like a fit for your school, contact us at hcjicomm@gmail.com to talk about your plan in detail.</p>
			<h3>Basic Guidelines</h3>
			<h4>About the logistics</h4>
			<ul>
				<li>Programs will take place inside Harvard Campus. All the facillities used during the program will be booked by HCJI.</li>
				<li>We ask most programs to be at most a day long.</li>
				<li>We do not provide any housing or meals. For meals, however, we can take the students to nearby restaurants in Harvard Square.</li>
				<li>We will not be responsible for any injuries/accidents happen during the program.</li>
			</ul>
			<h4>About the fee</h4>
		    <ul>
		    	<li>HCJI receives 20% commission from per-student-hour fee. For example, if School A pays HCJI $50 for having a Harvard student to be at the event for an hour, HCJI would receive $10, and the rest ($40) would go to the Harvard student.</li>
				<li>For any event, there should be a HCJI chaperone to make sure things are going well, especially for on campus events because we would be renting the rooms under the name of HCJI.</li>
					<ul>
						<li>The chaperoning fee on campus is $40/hr</li>
						<li>The chaperoning fee off campus is $35/hr</li>
					</ul>
			</ul>
			<h4>For the service fee</h4>
			<ul>
				<li>If the event is off-campus, there is no service fee</li>
				<li>If the events is on-campus, there would be service fee, which would be determined by how much work we need to do to host the event (such as booking rooms, etc.)</li>
				<li>If the length of a program exceeds a certain time period (e.g. 5 days), there should be an extra charge. One idea is to include it in the service fee.</li>
			</ul>
			<h4>Regarding deposit</h4>
			<ul>
				<li>Normal situation<li>
					<ul>
						<li>§  The deposit would be 50% of the total fee.</li>
						<li>§  The deposit should be paid 2 weeks before the first day of the program.</li>
					</ul>
				<li>Cancellation fee</li>
					<ul>
						<li>§  If the request to cancel a program comes 2 weeks before the first day of the program, there would be no cancelation fee.</li>
						<li>§  If the request to cancel a program comes within 2 weeks before the first day of the program, we will take half of the deposit.</li>
					</ul>
				<li>Fee for Changing the Content of the Contract</li>
					<ul>
						<li>§  In the case where the contract is signed by both sides, when the educational institution requests to change certain contents of the contract, a contract-changing fee of $100 will be added to the total cost.</li>
					</ul>
				<li>For on-campus room-booking that is done very early in advance (2 months in advance), we will charge a room-holding fee of $100, nonrefundable (not part of the deposit).</li>
			</ul>
			<h2>For students interested...</h2>
			<p>Please read the following basic guideline below. If this seems like a fit for you, join our HCJI Explore mailing list hcjiexplore@googlegroups.com</p>
			<h3>Basic Guidelines</h3>
			<ul>
				<li>You can either become a PA (project assistant) or a PM (project manager)
 of the program.</li>
				<li>PAs will come in on the day of the program to facilitate workshops and conduct campus tours. They will be responsible for ending the day with a success - enough inspiration for high school students. We ensure minimum time commitment before and after the program.
PMs will be responsible for the entire program, e.g finalizing the content, booking rooms,  e-mailing with the client, etc. HCJI will support you with each phase, and by the time you complete a program, you'll be able to have a clear understanding of how to push a program forward with Japanese clients.
Note that proficiency in Japanese is not required.</li>
			</ul>

			<div id="portfolio" class="container">
			</div>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="wrapper">
	<div id="banner" class="container"><img src="/assets/h-lab.png" width="1200" height="500" alt="" /></div>
	<div id="welcome" class="container">
    	
	<div class="title">
		<h2>We are Harvard College Japan Initiative</h2><br><br>
	 	<p>HCJI is a student-run organization dedicated to fostering greater interaction and understanding between students from the U.S. and Japan.</p>
	 	<a href="whoweare" class="button">Learn more about us</a>
	</div>
		
	</div>
	<div id="three-column" class="container">
		<div><span class="arrow-down"></span></div>
<!-- 		<div class="tbox">
			<div class="title">
				<h2>H-LAB</h2>
			</div>
			<img class="image" src="assets/masa.jpg" alt="" />
			<p>TODO Nga/ Nullam non wisi a sem semper eleifend. Donec mattis libero eget urna. Duis pretium velit ac suscipit mauris. Proin eu wisi suscipit nulla suscipit interdum.</p>
			<a href="static_pages/whatwedo#h-lab" class="button">Learn More</a> 		
		</div> -->
		<div class="tbox">
			<div class="title">
				<h2>HCJI Career Forum</h2>
			</div>
			<img class="image" src="assets/careers1.jpg" alt="" />
			<p>HCJI Career Forum is a 4-day series of events held before and during the annual Boston Career Forum (BCF) that serve as an opportunity for Harvard students and students who have been involved in Harvard programs in the past, to interact and network with companies in a more personal and casual environment.</p>
			<a href="http://www.harvardjapancareerforum.com/" class="button">Learn More</a> 
		</div>
		<div class="tbox">
			<div class="title">
				<h2>HCJI Explore</h2>
			</div>
			<img class="image" src="assets/campus1.jpg" alt="" />
			<p>HCJI Explore welcomes junior and senior high school students from all over Japan to "explore" the life at Harvard. We provide them with unique opportunities through our on-campus tours, presentations and workshops. All of these programs are created and coordinated by HCJI members and other Harvard students.</p>
			<a href="whatwedo#explore" class="button">Learn More</a> 
		</div>
		<div class="tbox">
			<div class="title">
				<h2>Dinner Series</h2>
			</div>
			<img class="image" src="assets/dinner.jpg" alt="" />
			<p>The Dinner Series, held in collaboration with the Reishcauer Institute of Japan Studies, invites renown professors and postdoctoral fellows to a specially catered dinner with 10 to 15 undergraduate students. We have been honored to have Professor Christine Yano, Dr. Nicolas Cisterna, and Professor Daniel Smith as our guests in 2014-2015.</p>
		<a href="" class="button">Coming Soon</a>
		</div>
		<div class="tbox">
			<div class="title">
				<h2>Wintersession Program</h2>
			</div>
			<img class="image" src="assets/wintersession.jpg" alt="" />
			<p>This year, we hope to create HCJI's very first wintersession program in which we can bring Harvard Student's to explore the rich festivites of New Years in Japan. Collaborating with an MIT based start up, this project will aim to bring an interactive english education program to students in Japan.</p>
			<a href="" class="button">Coming Soon</a>
		</div>
		<div class="tbox">
			<div class="title">
				<h2>Summer Conference</h2>
			</div>
			<img class="image" src="assets/tokyo.jpg" alt="" />
			<p>Through a collaboratiion with students at local Japanese universities, we aim to launch a new international conference bringing together talented youth from accross the globe. A selected Harvard delegation will visit Japan, to be emmersed in a week long dynamic program, with lectures, workshops, fieldtrips and more.</p>
			<a href="" class="button">Coming Soon</a> 
		</div>
		<div class="tbox">
			<div class="title">
				<h2>Summer Internships</h2>
			</div>
			<img class="image" src="assets/summerconf.jpg" alt="" />
			<p>HCJI Career Forum, a wonderful opportunity to meet and greet recruiters coming all the way from Japan, will be happening again this year! You may either join this forum as a potential applicant looking to network with recruiters, or also as a staff running the event.</p>
			<a href="" class="button">Coming Soon</a> 
		</div>
		<!-- <div class="tbox">
			<div class="title">
				<h2>Summer Education Program</h2>
			</div>
			<img class="image" src="assets/campus1.jpg" alt="" />
			<p>HCJI Explore welcomes junior and senior high school students from all over Japan to "explore" the life at Harvard. We provide them with unique opportunities through our on-campus tours, presentations and workshops. All of these programs are created and coordinated by HCJI members and other Harvard students.</p>
			<a href="" class="button">Coming Soon</a> 
		</div> -->
	</div>
</div>
<div id="footer">
	<div class="container">
		<div class="fbox">
			<span class="icon icon-envelope"></span>
			<h3>contact us:</h3>
			<p>hcji.comm@gmail.com</p>
			<p>   </p>
			<h3>join our mailing list:</h3>
			<p>sushi-talk@lists.hcs.harvard.edu</p>
		</div>
	</div>
</div>

app/views/static_pages/whatwedo.html.erb
<style>
.spacer{
	height: 80px;
}
.spacer2{
	height: 30px;
}
</style>

<div class="wrapper">
	<div id="whoweare" class="container">
		<div class="content">
			<div class="title">
				<h2>We run numerous activities on and off campus</h2>
			</div>
			<p>HCJI serves as a platform for people who are interested in participating in Japan-related activities. We are committed to fostering cultural exchange through students' active participation in various business-related, pre-professiona and educational activities.</p>
			<img src="assets/matsuri.jpg" alt="" />
		</div>
	</div>

	<div id="three-contents" class="container">
		<div><span class="arrow-down"></span></div>

		<!-- 		content1 -->

<!-- 		<div name="h-lab" class="content">
			<div class="title">
				<h2>H-LAB</h2>
			</div>
			<img class="image" src="assets/masa.jpg" alt="" />
			<div class="paragraphs">
				<p>TODO Nga/ Nullam non wisi a sem semper eleifend. Donec mattis libero eget urna. Duis pretium velit ac suscipit mauris. Proin eu wisi suscipit nulla suscipit interdum. Nullam non wisi a sem semper eleifend. Donec mattis libero eget urna. Duis pretium velit ac suscipit mauris. Proin eu wisi suscipit nulla suscipit interdum. Nullam non wisi a sem semper eleifend. Donec mattis libero eget urna. Duis pretium velit ac suscipit mauris. Proin eu wisi suscipit nulla suscipit interdum.</p>
				<p>For high school students and those generally interested...</p>
				<a href="http://tokyo.h-lab.co/" class="button">Official Website (Japanese)</a>
				<p>For Harvard and non Harvard college students interested in applying...<p>
				<a href="http://teach.h-lab.co/" class="button">Official Website for Potential Teachers (English)</a>
			</div>
		</div>
		 -->

		<!-- 		content2 -->

		<div id="hcf" class="content">
			<div class="title">
				<h2>HCJI Career Forum</h2>
			</div>
			<p><img class="image" src="assets/careers1.jpg" alt="" height="100px"/>HCJI Career Forum is a 4-day series of events held before and during the annual Boston Career Forum (BCF) that serve as an opportunity for Harvard students and students who have been involved in Harvard programs in the past, to interact and network with companies in a more personal and casual environment.</p>
			<p>We provide opportunities for recruiters and students to interact even before BCF begins so that students may network with representatives from various Japanese companies, and companies may do so likewise to their mutual benefit. In 2014, we held four formal information sessions and multiple social events between students and company representatives on Harvard’s campus. A total of 9 companies were represented.</p>
			<p>We also provide housing for non-Harvard students during BCF by connecting them with Harvard students who are willing to host in their dormitories.</p>
			<a href="careers" class="button">More Information</a>
		</div>

		<!-- 		content3 -->

		<div name="explore" class="content">
			<div class="title">
				<h2>HCJI Explore</h2>
			</div>
			<p><img class="image" src="assets/campus1.jpg" alt="" />HCJI Explore welcomes junior and senior high school students from all over Japan to "explore" the life at Harvard. We provide them with unique opportunities through our on-campus tours, presentations and workshops. All of these programs are created and coordinated by HCJI members and other Harvard students.

			We offer high schools interested in a more global curriculum a unique opportunity to incorporate on-the-ground experiences at Harvard into their programs. Programs will be developed in coordination with the schools so as to cater to the interests of both the students and the teachers at their request.</p>

			<a class="button">Coming Soon</a>
			<div class="spacer"></div>
		</div>


		<div name="more" class="content">
			<div class="title">
				<h2>And Lots More Coming Soon...</h2>
			</div>
		</div>
		
	</div>
</div>